#pragma once

#include <stdint.h>
#include <stddef.h>

/*
 * Per-channel network spec and per-model identity.
 *
 * These used to be #defines in device_config.h / wifi_config.h / ble_config.h,
 * which meant one firmware build per channel and a hand edit for every value.
 * The phone app now exports them — a device model's "Download firmware sketch"
 * produces cything_network_spec.h and cything_device_params.h — so the library
 * has to read them at runtime instead of baking them in.
 *
 * The mechanism is the one the claim certificate already uses (see
 * aws/claim_credentials.h): the library ships WEAK defaults equal to the old
 * macros, in device_config/cy_config.c, and an application that wants its own
 * values defines the same symbols strongly. Nothing dropped in => the firmware
 * behaves exactly as it did before.
 *
 * The application file is generated by the app; see main/cything_config.cpp.example
 * for ESP-IDF and examples/Basic/cything_config.ino for Arduino. That file must
 * #include CyThingEsp32.h: in C++ a namespace-scope `const` has INTERNAL linkage
 * unless a prior extern declaration is in scope, so without the include the
 * definitions are silently ignored and the weak defaults win.
 *
 * The device's own identity — deviceId, the provisioned sourceTerminalId, the
 * unit suffix from the eFuse MAC — is per unit and lives in NVS, not here.
 */

/* ---- channel network spec (cything_network_spec.h) ---------------------- */

/** Soft-AP SSID prefix; the unit suffix is appended (wifi/wifi_info_handler.c). */
extern const char     cy_ap_ssid_prefix[];
/** TCP pairing line prefixes, e.g. "ssid:" / "pass:" (tcp_server/pairing.c). */
extern const char     cy_router_ssid_prefix[];
extern const char     cy_router_pass_prefix[];
/** Local TCP command server / UDP discovery ports. */
extern const uint16_t cy_tcp_port;
extern const uint16_t cy_udp_port;
/** Discovery request token, e.g. "GET_INFO". */
extern const char     cy_scan_command[];
/** First field of the MQTT get-info reply, e.g. "ACK". */
extern const char     cy_scan_response[];
/** IPv4 multicast group the discovery query arrives on. */
extern const char     cy_multicast_ipv4[];
/**
 * BLE base UUID, 16 bytes in NimBLE's little-endian order (the string read
 * backwards), with the 16-bit service slot at indices 12/13 left zero.
 * ble_uuid128_from_base() fills the slot per service.
 */
extern const uint8_t  cy_ble_base_uuid128[16];

/* ---- device model identity (cything_device_params.h) -------------------- */

extern const char cy_device_name[];
/** Lower-case. The app matches a device on <sourceTerminalId>/<deviceType>. */
extern const char cy_device_type[];
extern const char cy_hardware_version[];
extern const char cy_firmware_version[];
/** Not read by the library today; exported so a model is fully described. */
extern const char cy_major_unique_id[];
extern const char cy_ota_username[];
extern const char cy_ota_password[];

/**
 * How many bytes of an incoming datagram must match cy_scan_command for it to
 * be a discovery query. Historically SCAN_COMMAND_LEN, i.e. sizeof - 3 —
 * strlen - 2, so "GET_INFO" matched on "GET_IN". Kept bug-for-bug: older
 * firmware and the app's own probes rely on the loose match.
 */
size_t cy_scan_command_len(void);

/** One INFO line with the spec actually in force — the proof a drop-in won. */
void cy_config_log(void);
