#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "esp_err.h"

/*
 * The device password: the one secret a new phone needs to pair over the
 * local link (doc/local-auth.md, step 1–2).
 *
 * The password itself is never stored. What is kept in NVS (namespace
 * "cy_sec") is an SRP-6a salt + verifier pair generated by esp_srp, so a
 * flash dump yields something that still has to be cracked like a password
 * hash, not a credential that logs in. The PAKE handler feeds the pair to
 * esp_srp_set_salt_verifier() for every pairing attempt.
 *
 * Guessing is rate-limited here, since a password can only be tested by
 * running the exchange against this device (that is the point of SRP):
 *   - per source IP:  DEVICE_PW_IP_MAX_FAILS consecutive failures lock that
 *     IP for DEVICE_PW_LOCK_BASE_S, doubling per further failure, capped at
 *     DEVICE_PW_LOCK_MAX_S. RAM only; one hostile phone cannot lock out
 *     everyone else.
 *   - globally:       DEVICE_PW_GLOBAL_MAX_FAILS consecutive failures from
 *     any mix of IPs lock the device the same way. Persisted, so a power
 *     cycle does not reset it.
 * A successful pairing clears both counters.
 *
 * Open device (no password set): PAKE runs with the model's public initial
 * password (cy_initial_password, device_config/cy_config.h) instead, so the
 * session is still encrypted. No rate limiting then — the password is public.
 */

#define DEVICE_PW_MIN_LEN          8
#define DEVICE_PW_MAX_LEN          64
#define DEVICE_PW_SALT_LEN         16
#define DEVICE_PW_VERIFIER_MAX     384   /* 3072-bit group */

#define DEVICE_PW_IP_MAX_FAILS     5
#define DEVICE_PW_GLOBAL_MAX_FAILS 20
#define DEVICE_PW_LOCK_BASE_S      60
#define DEVICE_PW_LOCK_MAX_S       3600

/* SRP identity ("I"). The password is per device, not per user, so every
 * client uses this fixed string. Must match the phone app byte for byte. */
#define DEVICE_PW_SRP_IDENTITY     "cy-device"

/* Load salt/verifier and the persisted lockout into RAM. Call once from
 * cything_begin() after NVS is up, before the TCP server starts. */
void device_password_init(void);

/* True once a password has been set (salt + verifier present). Without one
 * the device is open to all and PAKE uses cy_initial_password. */
bool device_password_is_set(void);

/* Derive and store a new salt/verifier for `password` (not NUL-terminated,
 * DEVICE_PW_MIN_LEN..DEVICE_PW_MAX_LEN bytes). Clears the fail counters.
 * ESP_ERR_INVALID_SIZE on a bad length. Safe to call from any task. */
esp_err_t device_password_set(const char *password, size_t len);

/* Remove the password (part of RESET). */
esp_err_t device_password_clear(void);

/* Borrow the pair PAKE should use: the stored one, or while none is set the
 * pair for cy_initial_password (derived on first use). False only if that
 * derivation failed. Pointers stay valid until the next set/clear. */
bool device_password_get(const uint8_t **salt, size_t *salt_len,
                         const uint8_t **verifier, size_t *verifier_len);

/* Seconds until `peer_ip` may attempt a pairing, 0 if it may now (always 0
 * while no password is set). */
uint32_t device_password_lock_remaining_s(uint32_t peer_ip);

/* Record the outcome of a proof check from `peer_ip`. */
void device_password_note_failure(uint32_t peer_ip);
void device_password_note_success(uint32_t peer_ip);
