#pragma once

#define BOOT_PARTION_TYPE         0x59
#define BOOT_PARTITION_SUBTYPE    0x0B

#define WIFI_INFO_PARTION_TYPE       0x41
#define WIFI_INFO_PARTITION_SUBTYPE  0x05

#define RESET_COUNTER_PARTITION_TYPE    0x42
#define RESET_COUNTER_PARTITION_SUBTYPE 0x06

#define FLASH_EMPTY_VALUE 0xFF